Выполнение урока 15
carrydan/codeby-devops pull request #23
Opened 2024-08-10 19:07 UTC by carrydan

2024-08-12 19:27 UTC, raguzin requested changes
реализация вероятно рабочая, но:
1. если мы имеем два модуля, то нужно это использовать. Для чего в модуле создания ВМ мы опять получаем инфо о подсетях, если мы это уже получили в модуле для сети.
2. вызов модулей нужно производить из "корневого" модуля, при этом при вызове модуля ВМ, ему передаем переменную с subnet_id определенным в зависимости от zone.
3. по best practice, в модуле должны присутствовать 3 файла variables, main, output И по ним разносится соответствующая конфигурация

2024-08-13 19:42 UTC, raguzin requested changes
Лучше, но выбор подсети должен выполняться не вручную, через передачу переменной из tfvars
```subnet_id = var.selected_subnet_id```
а автоматически на основе переданной zone.
Примерно так
```subnet_id = module.data_subnet.subnets_info[var.default_zone].id```
в зависимости от того, что там у тебя в subnets_info возвращается

2024-08-18 12:50 UTC, carrydan reviewed
@raguzin изменил

2024-08-19 09:30 UTC, raguzin approved these changes
ок, можно было обойтись без использования locals, выполняя вычисления сразу там, где потом подставляешь переменные localc

2024-08-19 10:16 UTC, merged